from pathlib import Path
import textwrap
import subprocess
import sys
import shutil
from .common import cfg, say, log, ok, warn, confirm, prompt

BASE_DIR = Path(__file__).resolve().parent.parent.parent


def copy_helper_scripts() -> None:
    """Copy helper scripts and install unified CLI."""
    log("Installing Paperless-NGX Bulletproof")
    
    # Copy backup and restore scripts to instance directory
    for name in ("backup.py", "restore.py"):
        src = BASE_DIR / "lib" / "modules" / name
        dst = Path(cfg.stack_dir) / name
        if src.exists():
            dst.write_text(src.read_text())
            dst.chmod(0o755)
        else:
            warn(f"Missing helper script: {src}")
    
    # Install the application library
    lib_dir = Path("/usr/local/lib/paperless-bulletproof")
    lib_dir.mkdir(parents=True, exist_ok=True)
    
    # Install main entry point
    src = BASE_DIR / "paperless.py"
    dst = lib_dir / "paperless.py"
    if src.exists():
        dst.write_text(src.read_text())
        dst.chmod(0o755)
    else:
        warn(f"Missing module: {src}")
    
    # Copy entire lib folder structure
    lib_src = BASE_DIR / "lib"
    lib_dst = lib_dir / "lib"
    if lib_src.exists():
        if lib_dst.exists():
            shutil.rmtree(lib_dst)
        shutil.copytree(lib_src, lib_dst)
    else:
        warn(f"Missing lib folder: {lib_src}")
    
    # Create main symlink
    main_link = Path("/usr/local/bin/paperless")
    if main_link.exists() or main_link.is_symlink():
        main_link.unlink()
    main_link.symlink_to(lib_dir / "paperless.py")
    
    ok("Installed 'paperless' command")


def restore_existing_backup_if_present() -> bool:
    remote = f"{cfg.rclone_remote_name}:{cfg.rclone_remote_path}"
    try:
        res = subprocess.run(
            ["rclone", "lsd", remote], capture_output=True, text=True, check=False
        )
    except Exception:
        return False
    if res.returncode != 0:
        return False
    snaps = [line.split()[-1].rstrip("/") for line in res.stdout.splitlines() if line.strip()]
    if not snaps:
        return False
    snaps = sorted(snaps)
    if not confirm("Existing backups found. Restore now?", True):
        return False
    for idx, name in enumerate(snaps, 1):
        say(f"  {idx}) {name}")
    choice = prompt("Choose snapshot number", str(len(snaps)))
    try:
        snap = snaps[int(choice) - 1]
    except Exception:
        snap = snaps[-1]
    say(f"Restoring chain: {snap}")
    subprocess.run(
        [sys.executable, str(BASE_DIR / "lib" / "modules" / "restore.py"), snap],
        check=True,
    )
    return True


def write_env_file() -> None:
    log(f"Writing {cfg.env_file}")
    if cfg.enable_traefik == "yes":
        paperless_url = f"https://{cfg.domain}"
    else:
        paperless_url = f"http://localhost:{cfg.http_port}"

    Path(cfg.stack_dir).mkdir(parents=True, exist_ok=True)
    content = textwrap.dedent(
        f"""
        # Generated by installer
        INSTANCE_NAME={cfg.instance_name}
        STACK_DIR={cfg.stack_dir}
        DATA_ROOT={cfg.data_root}

        # Data directories
        DIR_DATA={cfg.dir_data}
        DIR_MEDIA={cfg.dir_media}
        DIR_EXPORT={cfg.dir_export}
        DIR_CONSUME={cfg.dir_consume}
        DIR_DB={cfg.dir_db}

        PUID={cfg.puid}
        PGID={cfg.pgid}
        TZ={cfg.tz}

        PAPERLESS_ADMIN_USER={cfg.paperless_admin_user}
        PAPERLESS_ADMIN_PASSWORD={cfg.paperless_admin_password}
        PAPERLESS_URL={paperless_url}

        POSTGRES_VERSION={cfg.postgres_version}
        POSTGRES_DB={cfg.postgres_db}
        POSTGRES_USER={cfg.postgres_user}
        POSTGRES_PASSWORD={cfg.postgres_password}

        ENABLE_TRAEFIK={cfg.enable_traefik}
        DOMAIN={cfg.domain}
        LETSENCRYPT_EMAIL={cfg.letsencrypt_email}
        HTTP_PORT={cfg.http_port}

        RCLONE_REMOTE_NAME={cfg.rclone_remote_name}
        RCLONE_REMOTE_PATH={cfg.rclone_remote_path}
        RETENTION_DAYS={cfg.retention_days}
        CRON_FULL_TIME={cfg.cron_full_time}
        CRON_INCR_TIME={cfg.cron_incr_time}
        CRON_ARCHIVE_TIME={cfg.cron_archive_time}
        """
    ).strip() + "\n"
    Path(cfg.env_file).write_text(content)


def write_compose_file() -> None:
    log(f"Writing {cfg.compose_file} (Traefik={cfg.enable_traefik})")
    Path(cfg.stack_dir).mkdir(parents=True, exist_ok=True)
    if cfg.enable_traefik == "yes":
        compose = textwrap.dedent(
            f"""
            services:
              redis:
                image: redis:7-alpine
                restart: unless-stopped
                command: ["redis-server","--save","60","1","--loglevel","warning"]
                networks: [paperless]

              db:
                image: postgres:{cfg.postgres_version}-alpine
                restart: unless-stopped
                environment:
                  POSTGRES_DB: {cfg.postgres_db}
                  POSTGRES_USER: {cfg.postgres_user}
                  POSTGRES_PASSWORD: {cfg.postgres_password}
                volumes:
                  - {cfg.dir_db}:/var/lib/postgresql/data
                networks: [paperless]

              gotenberg:
                image: gotenberg/gotenberg:8
                restart: unless-stopped
                command: ["gotenberg","--chromium-disable-javascript=true"]
                networks: [paperless]

              tika:
                image: apache/tika:latest
                restart: unless-stopped
                networks: [paperless]

              paperless:
                image: ghcr.io/paperless-ngx/paperless-ngx:latest
                depends_on: [db, redis, gotenberg, tika]
                restart: unless-stopped
                environment:
                  PUID: {cfg.puid}
                  PGID: {cfg.pgid}
                  TZ: {cfg.tz}
                  PAPERLESS_REDIS: redis://redis:6379
                  PAPERLESS_DBHOST: db
                  PAPERLESS_DBPORT: 5432
                  PAPERLESS_DBNAME: {cfg.postgres_db}
                  PAPERLESS_DBUSER: {cfg.postgres_user}
                  PAPERLESS_DBPASS: {cfg.postgres_password}
                  PAPERLESS_ADMIN_USER: {cfg.paperless_admin_user}
                  PAPERLESS_ADMIN_PASSWORD: {cfg.paperless_admin_password}
                  PAPERLESS_URL: ${{PAPERLESS_URL}}
                  PAPERLESS_TIKA_ENABLED: "1"
                  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
                  PAPERLESS_TIKA_ENDPOINT: http://tika:9998
                  PAPERLESS_CONSUMER_POLLING: "10"
                volumes:
                  - {cfg.dir_data}:/usr/src/paperless/data
                  - {cfg.dir_media}:/usr/src/paperless/media
                  - {cfg.dir_export}:/usr/src/paperless/export
                  - {cfg.dir_consume}:/usr/src/paperless/consume
                labels:
                  - traefik.enable=true
                  - traefik.http.routers.paperless.rule=Host(`{cfg.domain}`)
                  - traefik.http.routers.paperless.entrypoints=websecure
                  - traefik.http.routers.paperless.tls.certresolver=le
                  - traefik.http.services.paperless.loadbalancer.server.port=8000
                networks: [paperless]

              traefik:
                image: traefik:v3.0
                restart: unless-stopped
                command:
                  - --providers.docker=true
                  - --providers.docker.exposedbydefault=false
                  - --entrypoints.web.address=:80
                  - --entrypoints.websecure.address=:443
                  - --certificatesresolvers.le.acme.httpchallenge=true
                  - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
                  - --certificatesresolvers.le.acme.email={cfg.letsencrypt_email}
                  - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
                ports:
                  - 80:80
                  - 443:443
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock:ro
                  - {cfg.stack_dir}/letsencrypt:/letsencrypt
                networks: [paperless]

            networks:
              paperless:
                name: paperless_net
            """
        ).strip() + "\n"
        Path(f"{cfg.stack_dir}/letsencrypt").mkdir(parents=True, exist_ok=True)
        Path(f"{cfg.stack_dir}/letsencrypt/acme.json").touch(exist_ok=True)
        Path(f"{cfg.stack_dir}/letsencrypt/acme.json").chmod(0o600)
    else:
        compose = textwrap.dedent(
            f"""
            services:
              redis:
                image: redis:7-alpine
                restart: unless-stopped
                command: ["redis-server","--save","60","1","--loglevel","warning"]
                networks: [paperless]

              db:
                image: postgres:{cfg.postgres_version}-alpine
                restart: unless-stopped
                environment:
                  POSTGRES_DB: {cfg.postgres_db}
                  POSTGRES_USER: {cfg.postgres_user}
                  POSTGRES_PASSWORD: {cfg.postgres_password}
                volumes:
                  - {cfg.dir_db}:/var/lib/postgresql/data
                networks: [paperless]

              gotenberg:
                image: gotenberg/gotenberg:8
                restart: unless-stopped
                command: ["gotenberg","--chromium-disable-javascript=true"]
                networks: [paperless]

              tika:
                image: apache/tika:latest
                restart: unless-stopped
                networks: [paperless]

              paperless:
                image: ghcr.io/paperless-ngx/paperless-ngx:latest
                depends_on: [db, redis, gotenberg, tika]
                restart: unless-stopped
                environment:
                  PUID: {cfg.puid}
                  PGID: {cfg.pgid}
                  TZ: {cfg.tz}
                  PAPERLESS_REDIS: redis://redis:6379
                  PAPERLESS_DBHOST: db
                  PAPERLESS_DBPORT: 5432
                  PAPERLESS_DBNAME: {cfg.postgres_db}
                  PAPERLESS_DBUSER: {cfg.postgres_user}
                  PAPERLESS_DBPASS: {cfg.postgres_password}
                  PAPERLESS_ADMIN_USER: {cfg.paperless_admin_user}
                  PAPERLESS_ADMIN_PASSWORD: {cfg.paperless_admin_password}
                  PAPERLESS_URL: ${{PAPERLESS_URL}}
                  PAPERLESS_TIKA_ENABLED: "1"
                  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
                  PAPERLESS_TIKA_ENDPOINT: http://tika:9998
                  PAPERLESS_CONSUMER_POLLING: "10"
                ports:
                  - {cfg.http_port}:8000
                volumes:
                  - {cfg.dir_data}:/usr/src/paperless/data
                  - {cfg.dir_media}:/usr/src/paperless/media
                  - {cfg.dir_export}:/usr/src/paperless/export
                  - {cfg.dir_consume}:/usr/src/paperless/consume
                networks: [paperless]

            networks:
              paperless:
                name: paperless_net
            """
        ).strip() + "\n"
    Path(cfg.compose_file).write_text(compose)


def bring_up_stack() -> None:
    log("Starting containers…")
    subprocess.run(
        [
            "docker",
            "compose",
            "--env-file",
            cfg.env_file,
            "-f",
            cfg.compose_file,
            "up",
            "-d",
        ],
        check=True,
        cwd=cfg.stack_dir,
    )


def install_cron_backup() -> None:
    log(
        f"Installing backup cron (full: {cfg.cron_full_time}, incr: {cfg.cron_incr_time}, archive: {cfg.cron_archive_time or 'disabled'})"
    )
    crontab = Path("/etc/crontab")
    lines = [
        l
        for l in (crontab.read_text().splitlines() if crontab.exists() else [])
        if f"{cfg.stack_dir}/backup.py" not in l
    ]
    full_line = (
        f"{cfg.cron_full_time} root {cfg.stack_dir}/backup.py full >> {cfg.stack_dir}/backup.log 2>&1"
    )
    incr_line = (
        f"{cfg.cron_incr_time} root {cfg.stack_dir}/backup.py incr >> {cfg.stack_dir}/backup.log 2>&1"
    )
    lines.extend([full_line, incr_line])
    if cfg.cron_archive_time:
        archive_line = (
            f"{cfg.cron_archive_time} root {cfg.stack_dir}/backup.py archive >> {cfg.stack_dir}/backup.log 2>&1"
        )
        lines.append(archive_line)
    crontab.write_text("\n".join(lines) + "\n")
    subprocess.run(["systemctl", "restart", "cron"], check=True)


def show_status() -> None:
    if cfg.enable_traefik == "yes":
        url = f"https://{cfg.domain}"
    else:
        url = f"http://localhost:{cfg.http_port}"
    print()
    ok(f"Paperless-ngx should be reachable at: {url}")
    print()
    say("Manage your instance with: paperless")
    print()

