from pathlib import Path
import textwrap
import subprocess
from .common import cfg, say, log, ok, warn

BASE_DIR = Path(__file__).resolve().parent.parent


def copy_helper_scripts() -> None:
    """Copy helper scripts and install bulletproof CLI."""
    log("Copying helper scripts and installing CLI")
    for name in ("backup.py", "restore.py"):
        src = BASE_DIR / "modules" / name
        dst = Path(cfg.stack_dir) / name
        if src.exists():
            dst.write_text(src.read_text())
            dst.chmod(0o755)
        else:
            warn(f"Missing helper script: {src}")

    bp_src = BASE_DIR / "tools" / "bulletproof.py"
    bp_dst = Path("/usr/local/bin/bulletproof")
    if bp_src.exists():
        bp_dst.write_text(bp_src.read_text())
        bp_dst.chmod(0o755)
    else:
        warn(f"Missing bulletproof CLI: {bp_src}")


def write_env_file() -> None:
    log(f"Writing {cfg.env_file}")
    if cfg.enable_traefik == "yes":
        paperless_url = f"https://{cfg.domain}"
    else:
        paperless_url = f"http://localhost:{cfg.http_port}"

    Path(cfg.stack_dir).mkdir(parents=True, exist_ok=True)
    content = textwrap.dedent(
        f"""
        # Generated by installer
        INSTANCE_NAME={cfg.instance_name}
        STACK_DIR={cfg.stack_dir}
        DATA_ROOT={cfg.data_root}

        PUID={cfg.puid}
        PGID={cfg.pgid}
        TZ={cfg.tz}

        PAPERLESS_ADMIN_USER={cfg.paperless_admin_user}
        PAPERLESS_ADMIN_PASSWORD={cfg.paperless_admin_password}
        PAPERLESS_URL={paperless_url}

        POSTGRES_VERSION={cfg.postgres_version}
        POSTGRES_DB={cfg.postgres_db}
        POSTGRES_USER={cfg.postgres_user}
        POSTGRES_PASSWORD={cfg.postgres_password}

        ENABLE_TRAEFIK={cfg.enable_traefik}
        DOMAIN={cfg.domain}
        LETSENCRYPT_EMAIL={cfg.letsencrypt_email}
        HTTP_PORT={cfg.http_port}

        RCLONE_REMOTE_NAME={cfg.rclone_remote_name}
        RCLONE_REMOTE_PATH={cfg.rclone_remote_path}
        RETENTION_DAYS={cfg.retention_days}
        """
    ).strip() + "\n"
    Path(cfg.env_file).write_text(content)


def write_compose_file() -> None:
    log(f"Writing {cfg.compose_file} (Traefik={cfg.enable_traefik})")
    Path(cfg.stack_dir).mkdir(parents=True, exist_ok=True)
    if cfg.enable_traefik == "yes":
        compose = textwrap.dedent(
            f"""
            services:
              redis:
                image: redis:7-alpine
                restart: unless-stopped
                command: ["redis-server","--save","60","1","--loglevel","warning"]
                networks: [paperless]

              db:
                image: postgres:{cfg.postgres_version}-alpine
                restart: unless-stopped
                environment:
                  POSTGRES_DB: {cfg.postgres_db}
                  POSTGRES_USER: {cfg.postgres_user}
                  POSTGRES_PASSWORD: {cfg.postgres_password}
                volumes:
                  - {cfg.dir_db}:/var/lib/postgresql/data
                networks: [paperless]

              gotenberg:
                image: gotenberg/gotenberg:8
                restart: unless-stopped
                command: ["gotenberg","--chromium-disable-javascript=true"]
                networks: [paperless]

              tika:
                image: ghcr.io/paperless-ngx/tika:latest
                restart: unless-stopped
                volumes:
                  - {cfg.dir_tika_cache}:/cache
                networks: [paperless]

              paperless:
                image: ghcr.io/paperless-ngx/paperless-ngx:latest
                depends_on: [db, redis, gotenberg, tika]
                restart: unless-stopped
                environment:
                  PUID: {cfg.puid}
                  PGID: {cfg.pgid}
                  TZ: {cfg.tz}
                  PAPERLESS_REDIS: redis://redis:6379
                  PAPERLESS_DBHOST: db
                  PAPERLESS_DBPORT: 5432
                  PAPERLESS_DBNAME: {cfg.postgres_db}
                  PAPERLESS_DBUSER: {cfg.postgres_user}
                  PAPERLESS_DBPASS: {cfg.postgres_password}
                  PAPERLESS_ADMIN_USER: {cfg.paperless_admin_user}
                  PAPERLESS_ADMIN_PASSWORD: {cfg.paperless_admin_password}
                  PAPERLESS_URL: ${{PAPERLESS_URL}}
                  PAPERLESS_TIKA_ENABLED: "1"
                  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
                  PAPERLESS_TIKA_ENDPOINT: http://tika:9998
                  PAPERLESS_CONSUMER_POLLING: "10"
                volumes:
                  - {cfg.dir_data}:/usr/src/paperless/data
                  - {cfg.dir_media}:/usr/src/paperless/media
                  - {cfg.dir_export}:/usr/src/paperless/export
                  - {cfg.dir_consume}:/usr/src/paperless/consume
                labels:
                  - traefik.enable=true
                  - traefik.http.routers.paperless.rule=Host(`{cfg.domain}`)
                  - traefik.http.routers.paperless.entrypoints=websecure
                  - traefik.http.routers.paperless.tls.certresolver=le
                  - traefik.http.services.paperless.loadbalancer.server.port=8000
                networks: [paperless]

              traefik:
                image: traefik:v3.0
                restart: unless-stopped
                command:
                  - --providers.docker=true
                  - --providers.docker.exposedbydefault=false
                  - --entrypoints.web.address=:80
                  - --entrypoints.websecure.address=:443
                  - --certificatesresolvers.le.acme.httpchallenge=true
                  - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
                  - --certificatesresolvers.le.acme.email={cfg.letsencrypt_email}
                  - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
                ports:
                  - 80:80
                  - 443:443
                volumes:
                  - /var/run/docker.sock:/var/run/docker.sock:ro
                  - {cfg.stack_dir}/letsencrypt:/letsencrypt
                networks: [paperless]

            networks:
              paperless:
                name: paperless_net
            """
        ).strip() + "\n"
        Path(f"{cfg.stack_dir}/letsencrypt").mkdir(parents=True, exist_ok=True)
        Path(f"{cfg.stack_dir}/letsencrypt/acme.json").touch(exist_ok=True)
        Path(f"{cfg.stack_dir}/letsencrypt/acme.json").chmod(0o600)
    else:
        compose = textwrap.dedent(
            f"""
            services:
              redis:
                image: redis:7-alpine
                restart: unless-stopped
                command: ["redis-server","--save","60","1","--loglevel","warning"]
                networks: [paperless]

              db:
                image: postgres:{cfg.postgres_version}-alpine
                restart: unless-stopped
                environment:
                  POSTGRES_DB: {cfg.postgres_db}
                  POSTGRES_USER: {cfg.postgres_user}
                  POSTGRES_PASSWORD: {cfg.postgres_password}
                volumes:
                  - {cfg.dir_db}:/var/lib/postgresql/data
                networks: [paperless]

              gotenberg:
                image: gotenberg/gotenberg:8
                restart: unless-stopped
                command: ["gotenberg","--chromium-disable-javascript=true"]
                networks: [paperless]

              tika:
                image: ghcr.io/paperless-ngx/tika:latest
                restart: unless-stopped
                volumes:
                  - {cfg.dir_tika_cache}:/cache
                networks: [paperless]

              paperless:
                image: ghcr.io/paperless-ngx/paperless-ngx:latest
                depends_on: [db, redis, gotenberg, tika]
                restart: unless-stopped
                environment:
                  PUID: {cfg.puid}
                  PGID: {cfg.pgid}
                  TZ: {cfg.tz}
                  PAPERLESS_REDIS: redis://redis:6379
                  PAPERLESS_DBHOST: db
                  PAPERLESS_DBPORT: 5432
                  PAPERLESS_DBNAME: {cfg.postgres_db}
                  PAPERLESS_DBUSER: {cfg.postgres_user}
                  PAPERLESS_DBPASS: {cfg.postgres_password}
                  PAPERLESS_ADMIN_USER: {cfg.paperless_admin_user}
                  PAPERLESS_ADMIN_PASSWORD: {cfg.paperless_admin_password}
                  PAPERLESS_URL: ${{PAPERLESS_URL}}
                  PAPERLESS_TIKA_ENABLED: "1"
                  PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
                  PAPERLESS_TIKA_ENDPOINT: http://tika:9998
                  PAPERLESS_CONSUMER_POLLING: "10"
                ports:
                  - {cfg.http_port}:8000
                volumes:
                  - {cfg.dir_data}:/usr/src/paperless/data
                  - {cfg.dir_media}:/usr/src/paperless/media
                  - {cfg.dir_export}:/usr/src/paperless/export
                  - {cfg.dir_consume}:/usr/src/paperless/consume
                networks: [paperless]

            networks:
              paperless:
                name: paperless_net
            """
        ).strip() + "\n"
    Path(cfg.compose_file).write_text(compose)


def bring_up_stack() -> None:
    log("Starting containers…")
    subprocess.run(
        [
            "docker",
            "compose",
            "--env-file",
            cfg.env_file,
            "-f",
            cfg.compose_file,
            "up",
            "-d",
        ],
        check=True,
        cwd=cfg.stack_dir,
    )


def install_cron_backup() -> None:
    log(f"Installing daily cron for backups ({cfg.cron_time})")
    cronline = f"{cfg.cron_time} root {cfg.stack_dir}/backup.py >> {cfg.stack_dir}/backup.log 2>&1"
    crontab = Path("/etc/crontab")
    content = crontab.read_text() if crontab.exists() else ""
    if cfg.stack_dir not in content:
        with crontab.open("a") as f:
            f.write(cronline + "\n")
        subprocess.run(["systemctl", "restart", "cron"], check=True)
    else:
        log("Cron line already present.")


def show_status() -> None:
    if cfg.enable_traefik == "yes":
        url = f"https://{cfg.domain}"
    else:
        url = f"http://localhost:{cfg.http_port}"
    print()
    ok(f"Paperless-ngx should be reachable at: {url}")

